// TODO: Create a more modular settings management system,
// For now, default get definitions is enough.
export const extensionSettings = {
  language: "",
  searchbar: false,
  animations: true,
  custombg: [],
  show_time: true,
  show_date: true,
  fmt_time: "",
  fmt_date: "",
  customfont: "",
  customfontgoogle: false,
  bookmarks: [],
  bookmarksFavicon: false,
  bookmarksTopSitesEnabled: false,
  bookmarksTopSitesAmount: 5,
  wEnable: false,
  wlat: 0,
  wlon: 0,
  wManualLocation: false,
  temp_type: "celcius",
  hexbg: false,
  showSettings: true,
  customcss: ""
}
